#ifndef SRC_FC_MANAGERS_FCCONFIG_H_
#define SRC_FC_MANAGERS_FCCONFIG_H_

/* Timer Channels */
#define SENSOR_AGT_READ_TIMER_CHANNEL 1
#define SENSOR_MAG_READ_TIMER_CHANNEL 2
#define SENSOR_BARO_READ_TIMER_CHANNEL 3

#define NOISE_FILTER_FFTX_TIMER_CHANNEL 4
#define NOISE_FILTER_FFTY_TIMER_CHANNEL 5
#define NOISE_FILTER_FFTZ_TIMER_CHANNEL 6
#define NOISE_FILTER_TIMER_CHANNEL 7

#define RC_READ_TIMER_CHANNEL 8
#define RC_TASK_TIMER_CHANNEL 9

#define ALT_MANAGER_TIMER_CHANNEL 10
#define POSITION_MANAGER_TIMER_CHANNEL 11

#define OUTPUT_CONTROL_TIMER_CHANNEL 12
#define DEBUG_TIMER_CHANNEL 13

/* Task Priorities */
#define RC_TASK_PRIORITY 3
#define NOISE_FILTER_TASK_PRIORITY 4
#define POSITION_MANAGEMENT_TASK_PRIORITY 5
#define ALT_MANAGEMENT_TASK_PRIORITY 5
#define INDICATOR_TASK_PRIORITY 5
#define DEBUG_TASK_PRIORITY 10

#define FC_STABLILIZATION_PERIOD 8.0f
#define FC_ARM_PERIOD 1.0f

#define DEBUG_ENABLED 0


#endif /* SRC_FC_MANAGERS_FCCONFIG_H_ */
